const steps=[...document.querySelectorAll('.step')];
const totalSteps=steps.length;
const progressText=document.querySelector('#progress-text');
const progressBar=document.querySelector('#progress-bar');
const progressTrack=document.querySelector('.progress-track');
const previewPanel=document.querySelector('#preview-panel');
const soundToggle=document.querySelector('#sound-toggle');
const toast=document.querySelector('#toast');
const lessonActivity=document.querySelector('#lesson-activity');
const activityLabel=document.querySelector('#activity-label');
const contentTitle=document.querySelector('#content-title');
const contentInstruction=document.querySelector('#content-instruction');
const activityBadge=document.querySelector('#activity-badge');
const activityBody=document.querySelector('#activity-body');
const activityFeedback=document.querySelector('#activity-feedback');
const nextActivity=document.querySelector('#next-activity');

/* Extra UI for the seven-part Unit 1 lesson. The original lookup.js remains active
   for text selection, pronunciation and Vietnamese meaning. */
const extraStyle=document.createElement('style');
extraStyle.textContent=`
.vocab-grid,.practice-grid,.challenge-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-top:18px}
.vocab-card,.mini-exercise,.grammar-box,.reading-box,.speaking-box,.challenge-box{background:#f7f9fc;border:1px solid #e2e8f0;border-radius:16px;padding:16px}
.vocab-card{display:flex;align-items:center;justify-content:space-between;gap:12px}.vocab-word{font:800 19px var(--display-font);color:#293b5c}.vocab-meta{font-size:12px;color:#718098;margin-top:3px}.vocab-meaning{font-size:13px;color:#51617a;margin-top:5px}.listen-word{border:0;background:#eaf0ff;color:#3959a9;border-radius:9px;padding:8px 10px;cursor:pointer;font-weight:800}.grammar-box{margin-top:18px;background:#fffdf4;border-color:#f1df9c}.grammar-box h3,.reading-box h3,.speaking-box h3,.challenge-box h3{font:800 19px var(--display-font);margin:0 0 8px;color:#293b5c}.grammar-rule{font-size:15px;line-height:1.6;color:#53627a}.formula{display:inline-block;background:#fff0c9;border-radius:9px;padding:6px 10px;font-weight:800;color:#8a6821;margin:5px 0}.example-line{padding:8px 10px;background:#fff;border-radius:9px;margin-top:8px;color:#42526c}.mini-exercise h3{font:800 17px var(--display-font);margin:0 0 10px}.mini-options{display:grid;grid-template-columns:1fr 1fr;gap:8px}.mini-options button{border:1px solid #dfe6ef;background:#fff;border-radius:9px;padding:9px;text-align:left;cursor:pointer;color:#40516d;font-weight:700}.mini-options button.correct{background:#eafff6;border-color:#62c7a5;color:#18795c}.mini-options button.wrong{background:#fff0ee;border-color:#ef9b91;color:#b24f46}.mini-explain{font-size:12px;line-height:1.5;color:#697890;margin-top:10px}.reading-box{margin-top:18px;background:#f8fbff}.reading-text{font-size:15px;line-height:1.75;color:#43536c;background:#fff;border-radius:12px;padding:15px}.reading-questions{display:grid;gap:10px;margin-top:14px}.reading-q{background:#fff;border:1px solid #e3e9f1;border-radius:12px;padding:12px}.reading-q p{font-weight:800;margin:0 0 8px}.speaking-box{margin-top:18px;background:#f2fff9;border-color:#c3eadc}.prompt-list{display:grid;gap:9px;margin:12px 0}.prompt-item{background:#fff;border-radius:10px;padding:10px;color:#4d5e75}.speaking-sample{background:#fff;border-left:4px solid #48b997;border-radius:8px;padding:12px;font-size:14px;line-height:1.6}.challenge-box{margin-top:18px;background:#fff5f1;border-color:#f4c9c1}.score-strip{display:flex;justify-content:space-between;align-items:center;background:#fff;border-radius:12px;padding:12px 14px;margin-bottom:12px}.score-strip strong{font:800 22px var(--display-font);color:#3959a9}.section-complete{display:flex;align-items:center;gap:12px;background:#edfff8;border:1px solid #bde8d8;border-radius:14px;padding:13px;margin-top:18px;color:#236e59}.section-complete .check{background:#40b998;color:#fff;border-radius:50%;width:30px;height:30px;display:grid;place-items:center;font-weight:800}.unit-note{font-size:12px;color:#7b879a;margin-top:12px;line-height:1.5}.audio-chip{border:0;background:#eef3ff;color:#3959a9;border-radius:9px;padding:7px 10px;font-weight:800;cursor:pointer}
@media(max-width:850px){.vocab-grid,.practice-grid,.challenge-grid{grid-template-columns:1fr}.mini-options{grid-template-columns:1fr}.lesson-layout{grid-template-columns:1fr}.lesson-nav{border-right:0}.step-list{grid-template-columns:repeat(2,1fr)}}
`;
document.head.appendChild(extraStyle);

const warmUpQuestions=[
 {prompt:'Which word is related to a school?',options:['school','banana','river','bedroom'],answer:'school',explanation:'“School” means “trường học”, so it is directly related to the topic My New School.'},
 {prompt:'You study with your classmates in a …',options:['classroom','kitchen','garden','bathroom'],answer:'classroom',explanation:'A classroom is a room where students learn together. The other choices are not normally places for a class.'},
 {prompt:'Which sentence is a natural way to introduce your new school?',options:['This is my new school.','This are my new school.','These is my new school.','This am my new school.'],answer:'This is my new school.',explanation:'We use “This is …” to introduce one thing. The other choices use the wrong form of be.'}
];

const vocabulary=[
 ['school','/skuːl/','trường học'],['classmate','/ˈklɑːs.meɪt/','bạn cùng lớp'],['classroom','/ˈklɑːs.ruːm/','phòng học'],['subject','/ˈsʌb.dʒɪkt/','môn học'],['uniform','/ˈjuː.nɪ.fɔːm/','đồng phục'],['calculator','/ˈkæl.kjə.leɪ.tər/','máy tính'],['compass','/ˈkʌm.pəs/','com-pa'],['schoolbag','/ˈskuːl.bæɡ/','cặp sách'],['textbook','/ˈtekst.bʊk/','sách giáo khoa'],['library','/ˈlaɪ.brer.i/','thư viện'],['playground','/ˈpleɪ.ɡraʊnd/','sân chơi'],['lesson','/ˈles.ən/','bài học']
];

const grammarQuestions=[
 {q:'My brother ___ to school every day.',opts:['go','goes','going','is go'],a:'goes',why:'“My brother” là chủ ngữ số ít nên động từ thường ở hiện tại đơn thêm -s/-es: goes.'},
 {q:'We ___ English on Monday.',opts:['study','studies','studying','is study'],a:'study',why:'“We” là chủ ngữ số nhiều nên dùng động từ nguyên mẫu: study.'},
 {q:'___ you usually play badminton after school?',opts:['Do','Does','Are','Is'],a:'Do',why:'Với chủ ngữ “you” ở câu hỏi hiện tại đơn, dùng trợ động từ Do.'},
 {q:'Lan ___ get up late on school days.',opts:["doesn't","don't","isn't","not"],a:"doesn't",why:'“Lan” là ngôi thứ ba số ít nên phủ định hiện tại đơn dùng doesn’t + động từ nguyên mẫu.'}
];

const practiceQuestions=[
 {q:'There ___ a computer in my classroom.',opts:['is','are','am','be'],a:'is',why:'“A computer” là danh từ số ít nên dùng There is.'},
 {q:'My friends ___ very friendly.',opts:['is','are','am','be'],a:'are',why:'“My friends” là số nhiều nên dùng are.'},
 {q:'She ___ English twice a week.',opts:['study','studies','studying','is study'],a:'studies',why:'She là ngôi thứ ba số ít; study đổi thành studies.'},
 {q:'We ___ wear uniforms at school.',opts:['usually','does','is','am'],a:'usually',why:'Usually là trạng từ tần suất, đứng trước động từ thường wear.'},
 {q:'Choose the correct sentence.',opts:['I have a new timetable.','I has a new timetable.','I having a new timetable.','I am have a new timetable.'],a:'I have a new timetable.',why:'Với I, động từ have giữ nguyên dạng have.'},
 {q:'Which item is used for drawing circles?',opts:['compass','calculator','schoolbag','textbook'],a:'compass',why:'A compass is used for drawing circles.'}
];

const readingQuestions=[
 {q:'Where is Nam’s new school?',opts:['In the city centre','Near his house','Next to a river','In the countryside'],a:'Near his house',why:'The passage says his new school is near his house.'},
 {q:'How many floors does the school have?',opts:['One','Two','Three','Four'],a:'Three',why:'The passage describes a three-floor school building.'},
 {q:'What does Nam like most?',opts:['The library','The canteen','The playground','The bus'],a:'The library',why:'Nam says the library is his favourite place because he loves reading.'}
];

let currentQuestion=0,score=0,answered=false;
let sectionScores={1:0,2:0,3:0,4:0,5:0,6:0,7:0};
let vocabDone=false,sectionQuestionIndex=0;

function shuffleOptions(a){const s=[...a];for(let i=s.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[s[i],s[j]]=[s[j],s[i]]}return s}
function speak(text){if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-GB';u.rate=.88;u.pitch=1;window.speechSynthesis.speak(u)}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function updateProgress(n){const safe=Math.min(Math.max(n,1),totalSteps),p=Math.round(safe/totalSteps*100);steps.forEach(x=>x.classList.toggle('is-active',Number(x.dataset.step)===safe));progressText.textContent=`${safe} / ${totalSteps}`;progressBar.style.width=`${p}%`;progressTrack.setAttribute('aria-label',`Tiến độ ${p}%`)}
function selectStep(n){updateProgress(n);renderStep(n)}
function setHeader(label,title,instruction,badge){activityLabel.textContent=label;contentTitle.textContent=title;contentInstruction.textContent=instruction;activityBadge.textContent=badge;activityFeedback.textContent=''}
function completion(text){return `<div class="section-complete"><span class="check">✓</span><div><strong>${text}</strong><div class="unit-note">Em có thể bôi đen bất kỳ từ hoặc cụm từ tiếng Anh để xem nghĩa, từ loại, IPA và nghe phát âm.</div></div></div>`}

function renderWarmUp(){
 const q=warmUpQuestions[currentQuestion],opts=shuffleOptions(q.options);answered=false;
 setHeader('KHỞI ĐỘNG • QUICK START','Let’s get started!',q.prompt,`${currentQuestion+1} / ${warmUpQuestions.length}`);
 nextActivity.textContent=currentQuestion===warmUpQuestions.length-1?'Hoàn thành ✓':'Câu tiếp theo →';
 activityBody.innerHTML=`<div class="question-card"><div class="question-number">Câu ${currentQuestion+1}</div><div class="question-prompt">${escapeHtml(q.prompt)}</div><div class="answer-grid">${opts.map((o,i)=>`<button class="answer-option" type="button" data-answer="${escapeHtml(o)}"><span>${String.fromCharCode(65+i)}</span>${escapeHtml(o)}</button>`).join('')}</div></div>`;
 activityBody.querySelectorAll('.answer-option').forEach(b=>b.addEventListener('click',()=>checkAnswer(b.dataset.answer,1,q)));
}
function checkAnswer(a,section,q){if(answered)return;answered=true;const buttons=[...activityBody.querySelectorAll('.answer-option')],chosen=buttons.find(b=>b.dataset.answer===a),correct=a===q.a||a===q.answer;buttons.forEach(b=>{b.disabled=true;if(b.dataset.answer===(q.a||q.answer))b.classList.add('is-correct')});if(chosen&&!correct)chosen.classList.add('is-wrong');if(correct){score++;sectionScores[section]++;activityFeedback.innerHTML=`<strong class="feedback-good">✓ Chính xác!</strong> ${q.why||q.explanation}`}else activityFeedback.innerHTML=`<strong class="feedback-bad">✗ Chưa đúng.</strong> Đáp án đúng là <b>${escapeHtml(q.a||q.answer)}</b>. ${q.why||q.explanation}`}
function showFinalWarmUp(){setHeader('KHỞI ĐỘNG • HOÀN THÀNH','Tuyệt vời! Em đã khởi động xong.','Hãy xem kết quả trước khi chuyển sang phần Từ vựng.','✓');activityBody.innerHTML=`<div class="result-card"><div class="result-score">${score}<span>/${warmUpQuestions.length}</span></div><div><h3>Kết quả khởi động</h3><p>${score===warmUpQuestions.length?'Rất tốt! Em đã sẵn sàng học Unit 1.':'Em hãy xem lại phần giải thích rồi tiếp tục nhé.'}</p></div></div>`+completion('Hoàn thành phần Khởi động!');activityFeedback.textContent='';nextActivity.textContent='Sang Từ vựng →'}

function renderVocabulary(){
 vocabDone=false;setHeader('TỪ VỰNG • VOCABULARY','My New School — Vocabulary','Học từ mới, nghe phát âm và ghi nhớ nghĩa tiếng Việt.',`${vocabulary.length} từ`);
 activityBody.innerHTML=`<div class="vocab-grid">${vocabulary.map((v,i)=>`<div class="vocab-card"><div><div class="vocab-word">${v[0]}</div><div class="vocab-meta">${v[1]} · noun</div><div class="vocab-meaning">${v[2]}</div></div><button class="listen-word" type="button" data-word="${v[0]}">🔊 Nghe UK</button></div>`).join('')}</div><div class="grammar-box"><h3>Mẹo ghi nhớ</h3><div class="grammar-rule">Hãy đọc từ → nghe lại → bôi đen từ để tra → đặt một câu ngắn với từ đó. Lặp lại nhiều lần sẽ giúp từ quen dần.</div></div>${completion('Bộ từ vựng Unit 1 đã sẵn sàng!')}`;
 activityBody.querySelectorAll('.listen-word').forEach(b=>b.addEventListener('click',()=>speak(b.dataset.word)));nextActivity.textContent='Sang Ngữ pháp →';vocabDone=true;
}

function renderGrammar(){sectionQuestionIndex=0;renderQuestionSection(3,'NGỮ PHÁP • GRAMMAR','Hiện tại đơn (Present Simple)','Học công thức trước, sau đó làm từng câu và xem giải thích.',grammarQuestions)}
function renderPractice(){sectionQuestionIndex=0;renderQuestionSection(4,'LUYỆN TẬP • PRACTICE','Practice Time!','Chọn đáp án phù hợp nhất. Hệ thống sẽ chỉ ra lý do chọn đáp án.',practiceQuestions)}
function renderQuestionSection(section,label,title,instruction,questions){
 const q=questions[sectionQuestionIndex];answered=false;setHeader(label,title,instruction,`${sectionQuestionIndex+1} / ${questions.length}`);nextActivity.textContent=sectionQuestionIndex===questions.length-1?'Hoàn thành ✓':'Câu tiếp theo →';
 activityBody.innerHTML=`${section===3?`<div class="grammar-box"><h3>Present Simple</h3><div class="grammar-rule">Dùng để nói về thói quen, lịch trình và sự việc lặp lại.<br><span class="formula">I / You / We / They + V</span><br><span class="formula">He / She / It + V-s / V-es</span><br><span class="formula">Do / Does + subject + V?</span></div><div class="example-line">I go to school every day. · She goes to school every day.</div></div>`:''}<div class="mini-exercise"><h3>Câu ${sectionQuestionIndex+1}. ${escapeHtml(q.q||q.prompt)}</h3><div class="mini-options">${shuffleOptions(q.opts||q.options).map(o=>`<button type="button" data-answer="${escapeHtml(o)}">${escapeHtml(o)}</button>`).join('')}</div><div class="mini-explain" id="mini-explain"></div></div>`;
 activityBody.querySelectorAll('.mini-options button').forEach(b=>b.addEventListener('click',()=>checkMiniAnswer(b,section,q)));
}
function checkMiniAnswer(button,section,q){if(answered)return;answered=true;const correct=button.dataset.answer===(q.a||q.answer),buttons=[...activityBody.querySelectorAll('.mini-options button')];buttons.forEach(b=>{b.disabled=true;if(b.dataset.answer===(q.a||q.answer))b.classList.add('correct')});if(!correct)button.classList.add('wrong');if(correct)sectionScores[section]++;document.querySelector('#mini-explain').innerHTML=correct?`<strong class="feedback-good">✓ Chính xác.</strong> ${q.why||q.explanation}`:`<strong class="feedback-bad">✗ Chưa đúng.</strong> Đáp án đúng: <b>${escapeHtml(q.a||q.answer)}</b>. ${q.why||q.explanation}`}
function showQuestionSectionResult(section,title,total){setHeader(`PHẦN ${section} • HOÀN THÀNH`,title,'Em đã hoàn thành các câu hỏi của phần này.','✓');activityBody.innerHTML=`<div class="result-card"><div class="result-score">${sectionScores[section]}<span>/${total}</span></div><div><h3>Kết quả phần học</h3><p>${sectionScores[section]===total?'Xuất sắc!':'Hãy xem lại phần giải thích và thử lại khi cần.'}</p></div></div>${completion(`Hoàn thành ${title}!`)}`;activityFeedback.textContent='';nextActivity.textContent=section<7?'Sang phần tiếp theo →':'Hoàn tất Unit 1'}

function renderReading(){setHeader('ĐỌC HIỂU • READING','My New School','Đọc đoạn văn ngắn, sau đó trả lời câu hỏi.',`1 / ${readingQuestions.length}`);answered=false;const passage=`Nam is a new student at Green Valley School. His school is near his house, so he walks to school every morning. The school has three floors and a large playground. His classroom is bright and comfortable. Nam likes the library most because he loves reading. He has English, Maths, Science and Art during the week. He is happy because his new classmates are friendly.`;activityBody.innerHTML=`<div class="reading-box"><h3>Read the passage</h3><div class="reading-text">${passage}</div><div class="reading-questions"><div class="reading-q"><p>Question 1. Where is Nam’s new school?</p><div class="mini-options">${shuffleOptions(readingQuestions[0].opts).map(o=>`<button type="button" data-answer="${escapeHtml(o)}">${escapeHtml(o)}</button>`).join('')}</div><div class="mini-explain" id="read-explain"></div></div></div></div>`;activityBody.querySelectorAll('.mini-options button').forEach(b=>b.addEventListener('click',()=>checkReading(b,0)));nextActivity.textContent='Câu tiếp theo →'}
function checkReading(button,index){if(answered)return;answered=true;const q=readingQuestions[index],correct=button.dataset.answer===q.a,buttons=[...activityBody.querySelectorAll('.mini-options button')];buttons.forEach(b=>{b.disabled=true;if(b.dataset.answer===q.a)b.classList.add('correct')});if(!correct)button.classList.add('wrong');if(correct)sectionScores[5]++;document.querySelector('#read-explain').innerHTML=correct?`<strong class="feedback-good">✓ Chính xác.</strong> ${q.why}`:`<strong class="feedback-bad">✗ Chưa đúng.</strong> Đáp án đúng: <b>${q.a}</b>. ${q.why}`;readingIndex=index}
let readingIndex=0;
function renderReadingQuestion(index){const q=readingQuestions[index];answered=false;activityBadge.textContent=`${index+1} / ${readingQuestions.length}`;activityBody.innerHTML=`<div class="reading-box"><h3>Read and choose</h3><div class="reading-text">Nam is a new student at Green Valley School. His school is near his house, so he walks to school every morning. The school has three floors and a large playground. His classroom is bright and comfortable. Nam likes the library most because he loves reading. He has English, Maths, Science and Art during the week. He is happy because his new classmates are friendly.</div><div class="reading-questions"><div class="reading-q"><p>Question ${index+1}. ${q.q}</p><div class="mini-options">${shuffleOptions(q.opts).map(o=>`<button type="button" data-answer="${escapeHtml(o)}">${escapeHtml(o)}</button>`).join('')}</div><div class="mini-explain" id="read-explain"></div></div></div></div>`;activityBody.querySelectorAll('.mini-options button').forEach(b=>b.addEventListener('click',()=>checkReading(b,index)));nextActivity.textContent=index===readingQuestions.length-1?'Hoàn thành ✓':'Câu tiếp theo →'}

function renderSpeaking(){setHeader('NÓI • SPEAKING','Talk about your new school','Dùng từ gợi ý để nói. Động từ được cho ở dạng nguyên mẫu để em tự vận dụng.', 'Speaking');activityBody.innerHTML=`<div class="speaking-box"><h3>Task: Introduce your school</h3><p class="unit-note">Nói 5–6 câu. Hãy dùng các từ gợi ý dưới đây và tự chia động từ khi cần.</p><div class="prompt-list"><div class="prompt-item"><b>name</b> · <b>be</b> · my school · new</div><div class="prompt-item"><b>go</b> · school · every day</div><div class="prompt-item"><b>study</b> · English · twice a week</div><div class="prompt-item"><b>like</b> · library · because · read</div><div class="prompt-item"><b>play</b> · badminton · after school</div></div><div class="speaking-sample"><strong>Sample:</strong> My school is Green Valley School. I go to school every day. I study English twice a week. I like the library because I love reading. I play badminton after school.</div><div style="margin-top:12px"><button class="audio-chip" type="button" id="speak-sample">🔊 Nghe bài mẫu</button></div></div>${completion('Em đã có khung Speaking để luyện nói!')}`;document.querySelector('#speak-sample').addEventListener('click',()=>speak('My school is Green Valley School. I go to school every day. I study English twice a week. I like the library because I love reading. I play badminton after school.'));nextActivity.textContent='Sang Thử thách →'}

function renderChallenge(){sectionQuestionIndex=0;const qs=[...practiceQuestions.slice(0,3),...grammarQuestions.slice(0,2)];renderChallengeQuestion(qs)}
function renderChallengeQuestion(qs){const q=qs[sectionQuestionIndex];answered=false;setHeader('THỬ THÁCH • CHALLENGE','Unit 1 Master Challenge','5 câu tổng hợp. Hãy tự tin vận dụng từ vựng và ngữ pháp.',`${sectionQuestionIndex+1} / ${qs.length}`);activityBody.innerHTML=`<div class="challenge-box"><div class="score-strip"><span>Điểm thử thách</span><strong>${sectionScores[7]} / ${qs.length}</strong></div><h3>${escapeHtml(q.q)}</h3><div class="mini-options">${shuffleOptions(q.opts).map(o=>`<button type="button" data-answer="${escapeHtml(o)}">${escapeHtml(o)}</button>`).join('')}</div><div class="mini-explain" id="challenge-explain"></div></div>`;activityBody.querySelectorAll('.mini-options button').forEach(b=>b.addEventListener('click',()=>checkChallenge(b,q)));nextActivity.textContent=sectionQuestionIndex===qs.length-1?'Hoàn thành ✓':'Câu tiếp theo →'}
function checkChallenge(button,q){if(answered)return;answered=true;const correct=button.dataset.answer===q.a,buttons=[...activityBody.querySelectorAll('.mini-options button')];buttons.forEach(b=>{b.disabled=true;if(b.dataset.answer===q.a)b.classList.add('correct')});if(!correct)button.classList.add('wrong');if(correct)sectionScores[7]++;document.querySelector('#challenge-explain').innerHTML=correct?`<strong class="feedback-good">✓ Chính xác!</strong> ${q.why}`:`<strong class="feedback-bad">✗ Chưa đúng.</strong> Đáp án: <b>${q.a}</b>. ${q.why}`}

function renderPlaceholder(n){const names=['Khởi động','Từ vựng','Ngữ pháp','Luyện tập','Đọc hiểu','Nói','Thử thách'];setHeader(`PHẦN ${String(n).padStart(2,'0')}`,names[n-1],'Nội dung Unit 1 theo từng bước.',`${n} / ${totalSteps}`);activityBody.innerHTML='<div class="coming-card"><span class="coming-icon">✦</span><div><h3>Nội dung đang được xây dựng</h3><p>Khung tương tác của phần này đã sẵn sàng.</p></div></div>';nextActivity.textContent=n<totalSteps?'Sang phần tiếp theo →':'Hoàn tất Unit 1'}
function renderStep(n){previewPanel.classList.toggle('show',n===1);if(n===1)renderWarmUp();else if(n===2)renderVocabulary();else if(n===3)renderGrammar();else if(n===4)renderPractice();else if(n===5){readingIndex=0;renderReadingQuestion(0)}else if(n===6)renderSpeaking();else if(n===7)renderChallenge();}

steps.forEach(s=>s.addEventListener('click',()=>{selectStep(Number(s.dataset.step));lessonActivity.scrollIntoView({behavior:'smooth',block:'center'})}));
document.querySelector('#start-activity').addEventListener('click',()=>{currentQuestion=0;score=0;selectStep(1);lessonActivity.scrollIntoView({behavior:'smooth',block:'center'})});
nextActivity.addEventListener('click',()=>{
 const active=Number(document.querySelector('.step.is-active')?.dataset.step||1);
 if(active===1){if(currentQuestion<warmUpQuestions.length-1){if(!answered){activityFeedback.innerHTML='<strong class="feedback-bad">Hãy chọn một đáp án trước nhé.</strong>';return}currentQuestion++;renderWarmUp();return}if(currentQuestion===warmUpQuestions.length-1&&answered){showFinalWarmUp();return}if(currentQuestion===warmUpQuestions.length-1){selectStep(2);return}}
 if(active===2){selectStep(3);return}
 if(active===3){if(sectionQuestionIndex<grammarQuestions.length-1){if(!answered){activityFeedback.innerHTML='<strong class="feedback-bad">Hãy chọn một đáp án trước nhé.</strong>';return}sectionQuestionIndex++;renderQuestionSection(3,'NGỮ PHÁP • GRAMMAR','Hiện tại đơn (Present Simple)','Học công thức trước, sau đó làm từng câu và xem giải thích.',grammarQuestions);return}if(answered){showQuestionSectionResult(3,'Ngữ pháp',grammarQuestions.length);return}return}
 if(active===4){if(sectionQuestionIndex<practiceQuestions.length-1){if(!answered){activityFeedback.innerHTML='<strong class="feedback-bad">Hãy chọn một đáp án trước nhé.</strong>';return}sectionQuestionIndex++;renderQuestionSection(4,'LUYỆN TẬP • PRACTICE','Practice Time!','Chọn đáp án phù hợp nhất. Hệ thống sẽ chỉ ra lý do chọn đáp án.',practiceQuestions);return}if(answered){showQuestionSectionResult(4,'Luyện tập',practiceQuestions.length);return}return}
 if(active===5){if(readingIndex<readingQuestions.length-1){if(!answered){activityFeedback.innerHTML='<strong class="feedback-bad">Hãy chọn một đáp án trước nhé.</strong>';return}readingIndex++;renderReadingQuestion(readingIndex);return}if(answered){showQuestionSectionResult(5,'Đọc hiểu',readingQuestions.length);return}return}
 if(active===6){selectStep(7);return}
 if(active===7){const qs=[...practiceQuestions.slice(0,3),...grammarQuestions.slice(0,2)];if(sectionQuestionIndex<qs.length-1){if(!answered){activityFeedback.innerHTML='<strong class="feedback-bad">Hãy chọn một đáp án trước nhé.</strong>';return}sectionQuestionIndex++;renderChallengeQuestion(qs);return}if(answered){setHeader('UNIT 1 • HOÀN THÀNH','Chúc mừng! Em đã hoàn thành Unit 1.','Hãy xem lại những từ và câu em còn chưa chắc.', '✓');activityBody.innerHTML=`<div class="result-card"><div class="result-score">${sectionScores[7]}<span>/5</span></div><div><h3>Thử thách hoàn tất</h3><p>Em đã đi qua đủ 7 bước của Unit 1. Hãy tiếp tục luyện tập và tra từ khi quên nhé!</p></div></div>${completion('Unit 1 — My New School đã hoàn thành!')}`;nextActivity.textContent='Học lại từ đầu ↻';return}return}
});
soundToggle.addEventListener('click',()=>{const enabled=soundToggle.getAttribute('aria-pressed')!=='true';soundToggle.setAttribute('aria-pressed',String(enabled));toast.textContent=enabled?'Đã bật âm thanh hướng dẫn!':'Đã tắt âm thanh hướng dẫn!';toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2600)});
renderStep(1);
