const steps=[...document.querySelectorAll('.step')];
const totalSteps=steps.length;
const progressText=document.querySelector('#progress-text');
const progressBar=document.querySelector('#progress-bar');
const progressTrack=document.querySelector('.progress-track');
const previewPanel=document.querySelector('#preview-panel');
const soundToggle=document.querySelector('#sound-toggle');
const toast=document.querySelector('#toast');
const lessonActivity=document.querySelector('#lesson-activity');
const activityLabel=document.querySelector('#activity-label');
const contentTitle=document.querySelector('#content-title');
const contentInstruction=document.querySelector('#content-instruction');
const activityBadge=document.querySelector('#activity-badge');
const activityBody=document.querySelector('#activity-body');
const activityFeedback=document.querySelector('#activity-feedback');
const nextActivity=document.querySelector('#next-activity');

/* Unit 1 interactive engine: MCQ + writing + vocabulary audio + advanced challenge. */
const extraStyle=document.createElement('style');
extraStyle.textContent=`
.vocab-grid,.practice-grid,.challenge-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-top:18px}
.vocab-card,.mini-exercise,.grammar-box,.reading-box,.speaking-box,.challenge-box,.writing-card{background:#f7f9fc;border:1px solid #e2e8f0;border-radius:16px;padding:16px}
.vocab-card{display:flex;align-items:center;justify-content:space-between;gap:12px}.vocab-word{font:800 19px var(--display-font);color:#293b5c}.vocab-meta{font-size:12px;color:#718098;margin-top:3px}.vocab-meaning{font-size:13px;color:#51617a;margin-top:5px}.listen-word{border:0;background:#eaf0ff;color:#3959a9;border-radius:9px;padding:8px 10px;cursor:pointer;font-weight:800}
.grammar-box{margin-top:18px;background:#fffdf4;border-color:#f1df9c}.grammar-box h3,.reading-box h3,.speaking-box h3,.challenge-box h3,.writing-card h3{font:800 19px var(--display-font);margin:0 0 8px;color:#293b5c}.grammar-rule{font-size:15px;line-height:1.6;color:#53627a}.formula{display:inline-block;background:#fff0c9;border-radius:9px;padding:6px 10px;font-weight:800;color:#8a6821;margin:5px 0}.example-line{padding:8px 10px;background:#fff;border-radius:9px;margin-top:8px;color:#42526c}
.mini-exercise{margin-top:12px;background:#fff}.mini-exercise h3{font:800 17px var(--display-font);margin:0 0 10px}.mini-options{display:grid;grid-template-columns:1fr 1fr;gap:8px}.mini-options button{border:1px solid #dfe6ef;background:#fff;border-radius:9px;padding:9px;text-align:left;cursor:pointer;color:#40516d;font-weight:700}.mini-options button.correct{background:#eafff6;border-color:#62c7a5;color:#18795c}.mini-options button.wrong{background:#fff0ee;border-color:#ef9b91;color:#b24f46}.mini-explain{font-size:12px;line-height:1.5;color:#697890;margin-top:10px}
.writing-card{margin-top:12px;background:#fffdfb}.writing-card .writing-prompt{font-size:15px;line-height:1.55;color:#40516d;margin:5px 0 11px}.writing-input{width:100%;min-height:44px;border:1px solid #dce4ee;border-radius:10px;background:#fff;padding:10px 12px;font:600 14px var(--body-font);color:#344765;resize:vertical}.writing-input:focus{outline:2px solid #c8d5f5;border-color:#6e86c2}.writing-actions{display:flex;gap:8px;align-items:center;margin-top:9px;flex-wrap:wrap}.check-writing{border:0;background:#3959a9;color:#fff;border-radius:9px;padding:9px 13px;font-weight:800;cursor:pointer}.sample-answer{display:none;margin-top:10px;padding:10px 12px;background:#eefbf6;border:1px solid #bde7d8;border-radius:10px;color:#2f6857;font-size:13px;line-height:1.5}.sample-answer.show{display:block}.writing-result{font-size:12px;font-weight:700}.writing-result.good{color:#188260}.writing-result.bad{color:#c5564c}
.reading-box{margin-top:18px;background:#f8fbff}.reading-text{font-size:15px;line-height:1.75;color:#43536c;background:#fff;border-radius:12px;padding:15px}.reading-questions{display:grid;gap:10px;margin-top:14px}.reading-q{background:#fff;border:1px solid #e3e9f1;border-radius:12px;padding:12px}.reading-q p{font-weight:800;margin:0 0 8px}
.speaking-box{margin-top:18px;background:#f2fff9;border-color:#c3eadc}.prompt-list{display:grid;gap:9px;margin:12px 0}.prompt-item{background:#fff;border-radius:10px;padding:10px;color:#4d5e75}.speaking-sample{background:#fff;border-left:4px solid #48b997;border-radius:8px;padding:12px;font-size:14px;line-height:1.6}.speaking-note{font-size:12px;color:#63748b;margin-top:10px}
.challenge-box{margin-top:18px;background:#fff5f1;border-color:#f4c9c1}.challenge-intro{font-size:13px;color:#687890;line-height:1.55}.score-strip{display:flex;justify-content:space-between;align-items:center;background:#fff;border-radius:12px;padding:12px 14px;margin-bottom:12px}.score-strip strong{font:800 22px var(--display-font);color:#3959a9}.challenge-section-title{font:800 15px var(--display-font);color:#6c5a56;margin:18px 0 8px}.section-complete{display:flex;align-items:center;gap:12px;background:#edfff8;border:1px solid #bde8d8;border-radius:14px;padding:13px;margin-top:18px;color:#236e59}.section-complete .check{background:#40b998;color:#fff;border-radius:50%;width:30px;height:30px;display:grid;place-items:center;font-weight:800}.unit-note{font-size:12px;color:#7b879a;margin-top:12px;line-height:1.5}.audio-chip{border:0;background:#eef3ff;color:#3959a9;border-radius:9px;padding:7px 10px;font-weight:800;cursor:pointer}
@media(max-width:850px){.vocab-grid,.practice-grid,.challenge-grid{grid-template-columns:1fr}.mini-options{grid-template-columns:1fr}.lesson-layout{grid-template-columns:1fr}.lesson-nav{border-right:0}.step-list{grid-template-columns:repeat(2,1fr)}}`;
document.head.appendChild(extraStyle);

const warmUpQuestions=[
 {prompt:'Which word is related to a school?',options:['school','banana','river','bedroom'],answer:'school',explanation:'“School” means “trường học”, so it is directly related to My New School.'},
 {prompt:'You study with your classmates in a …',options:['classroom','kitchen','garden','bathroom'],answer:'classroom',explanation:'A classroom is a room where students learn together.'},
 {prompt:'Which sentence is correct?',options:['This is my new school.','This are my new school.','These is my new school.','This am my new school.'],answer:'This is my new school.',explanation:'“This is …” is used to introduce one thing.'}
];
const vocabulary=[
 ['school','/skuːl/','noun','trường học'],['classmate','/ˈklɑːs.meɪt/','noun','bạn cùng lớp'],['classroom','/ˈklɑːs.ruːm/','noun','phòng học'],['subject','/ˈsʌb.dʒɪkt/','noun','môn học'],['uniform','/ˈjuː.nɪ.fɔːm/','noun','đồng phục'],['calculator','/ˈkæl.kjə.leɪ.tər/','noun','máy tính'],['compass','/ˈkʌm.pəs/','noun','com-pa'],['schoolbag','/ˈskuːl.bæɡ/','noun','cặp sách'],['textbook','/ˈtekst.bʊk/','noun','sách giáo khoa'],['library','/ˈlaɪ.brer.i/','noun','thư viện'],['playground','/ˈpleɪ.ɡraʊnd/','noun','sân chơi'],['lesson','/ˈles.ən/','noun','bài học']
];
const grammarQuestions=[
 {q:'My brother ___ to school every day.',opts:['go','goes','going','is go'],a:'goes',why:'“My brother” là chủ ngữ số ít nên động từ hiện tại đơn thêm -s/-es: goes.'},
 {q:'We ___ English on Monday.',opts:['study','studies','studying','is study'],a:'study',why:'“We” là chủ ngữ số nhiều nên dùng động từ nguyên mẫu: study.'},
 {q:'___ you usually play badminton after school?',opts:['Do','Does','Are','Is'],a:'Do',why:'Với “you” ở hiện tại đơn, câu hỏi dùng Do.'},
 {q:'Lan ___ get up late on school days.',opts:["doesn't","don't","isn't","not"],a:"doesn't",why:'Lan là ngôi thứ ba số ít nên dùng doesn’t + động từ nguyên mẫu.'}
];
const practiceQuestions=[
 {q:'There ___ a computer in my classroom.',opts:['is','are','am','be'],a:'is',why:'“A computer” là số ít nên dùng There is.'},
 {q:'My friends ___ very friendly.',opts:['is','are','am','be'],a:'are',why:'“My friends” là số nhiều nên dùng are.'},
 {q:'She ___ English twice a week.',opts:['study','studies','studying','is study'],a:'studies',why:'She là ngôi thứ ba số ít; study đổi thành studies.'},
 {q:'We ___ wear uniforms at school.',opts:['usually','does','is','am'],a:'usually',why:'Usually là trạng từ tần suất, đứng trước động từ thường wear.'},
 {q:'Choose the correct sentence.',opts:['I have a new timetable.','I has a new timetable.','I having a new timetable.','I am have a new timetable.'],a:'I have a new timetable.',why:'Với I, động từ have giữ nguyên dạng.'},
 {q:'Which item is used for drawing circles?',opts:['compass','calculator','schoolbag','textbook'],a:'compass',why:'A compass is used for drawing circles.'}
];
const writingQuestions=[
 {prompt:'Viết lại câu ở dạng phủ định: “I like my new school.”',answer:"I don't like my new school.",keywords:['i','don\'t','like','my','new','school'],note:'Dùng don’t với chủ ngữ I.'},
 {prompt:'Sắp xếp thành câu đúng: “usually / I / at / get up / 6 o’clock”.',answer:"I usually get up at 6 o'clock.",keywords:['i','usually','get up','at','6'],note:'Trạng từ usually đứng trước động từ thường.'},
 {prompt:'Viết một câu tiếng Anh có từ “classmate”.',answer:'My classmate is friendly.',keywords:['classmate'],note:'Câu mẫu có thể thay đổi nếu câu của em đúng ngữ pháp và dùng đúng từ.'},
 {prompt:'Viết 2 câu giới thiệu ngắn về trường mới của em.',answer:'My new school is big. I like my teachers.',keywords:['my','school','i','like'],note:'Có thể viết câu khác với mẫu, miễn đúng ngữ pháp và đúng chủ đề.'}
];
const challengeMCQ=[
 {q:'Choose the correct sentence.',opts:['She don’t like Maths.','She doesn’t likes Maths.','She doesn’t like Maths.','She not like Maths.'],a:'She doesn’t like Maths.',why:'Sau doesn’t, động từ phải trở về nguyên mẫu: like.'},
 {q:'Which sentence has the correct word order?',opts:['I always am on time.','I am always on time.','Always I am on time.','I on time am always.'],a:'I am always on time.',why:'Với động từ be, trạng từ tần suất thường đứng sau be.'},
 {q:'___ there any books on the desk?',opts:['Is','Are','Do','Does'],a:'Are',why:'Books là danh từ số nhiều nên dùng Are there …?'.replace('Books','“Books”)},
 {q:'Which question is correct?',opts:['Where your school is?','Where is your school?','Where does your school?','Where your school does?'],a:'Where is your school?',why:'Với be, từ để hỏi đứng trước be: Where is …?'},
 {q:'Nam ___ his homework before dinner every day.',opts:['do','does','doing','is do'],a:'does',why:'Nam là ngôi thứ ba số ít nên do đổi thành does.'},
 {q:'Which word is closest in meaning to “classmate”?',opts:['teacher','student in the same class','school building','subject'],a:'student in the same class',why:'Classmate là người học cùng lớp với em.'}
];
const challengeWriting=[
 {prompt:'Viết câu hỏi cho phần gạch chân: “My school is near my house.” (gạch chân “near my house”)',answer:'Where is your school?',keywords:['where','is','your','school'],note:'Hỏi địa điểm dùng Where + be.'},
 {prompt:'Viết lại câu: “I go to school by bike.” → Đổi chủ ngữ thành “Lan”.',answer:'Lan goes to school by bike.',keywords:['lan','goes','school','bike'],note:'Lan là ngôi thứ ba số ít nên go → goes.'},
 {prompt:'Viết 3 câu về một ngày đi học của em. Dùng ít nhất một trạng từ tần suất.',answer:'I usually get up at 6. I go to school at 7. I often play with my classmates.',keywords:['i','school'],note:'Bài của em có thể khác mẫu. Hãy kiểm tra chủ ngữ, động từ và trạng từ tần suất.'},
 {prompt:'Viết một câu có cấu trúc “There is/There are” để mô tả lớp học.',answer:'There are twenty desks in my classroom.',keywords:['there','classroom'],note:'There is dùng với số ít; There are dùng với số nhiều.'}
];
let currentQuestion=0,score=0,answered=false;
function shuffleOptions(a){const s=[...a];for(let i=s.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[s[i],s[j]]=[s[j],s[i]]}return s}
function speak(text){if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-GB';u.rate=.88;u.pitch=1;window.speechSynthesis.speak(u)}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function normalize(s){return String(s).toLowerCase().replace(/[’‘]/g,"'").replace(/[.,!?;:"“”]/g,' ').replace(/\s+/g,' ').trim()}
function setHeader(label,title,instruction,badge){activityLabel.textContent=label;contentTitle.textContent=title;contentInstruction.textContent=instruction;activityBadge.textContent=badge;activityFeedback.textContent=''}
function completion(text){return `<div class="section-complete"><span class="check">✓</span><div><strong>${text}</strong><div class="unit-note">Em có thể bôi đen từ/cụm từ tiếng Anh để xem nghĩa, từ loại, IPA và nghe phát âm.</div></div></div>`}
function updateProgress(n){const p=Math.round(n/totalSteps*100);steps.forEach(x=>x.classList.toggle('is-active',Number(x.dataset.step)===n));progressText.textContent=`${n} / ${totalSteps}`;progressBar.style.width=`${p}%`;progressTrack.setAttribute('aria-label',`Tiến độ ${p}%`)}
function selectStep(n){updateProgress(n);renderStep(n)}
function renderWarmUp(){
 const q=warmUpQuestions[currentQuestion],opts=shuffleOptions(q.options);answered=false;
 setHeader('KHỞI ĐỘNG • QUICK START','Let’s get started!',q.prompt,`${currentQuestion+1} / ${warmUpQuestions.length}`);
 nextActivity.textContent=currentQuestion===warmUpQuestions.length-1?'Hoàn thành ✓':'Câu tiếp theo →';
 activityBody.innerHTML=`<div class="question-card"><div class="question-number">Câu ${currentQuestion+1}</div><div class="question-prompt">${esc(q.prompt)}</div><div class="answer-grid">${opts.map((o,i)=>`<button class="answer-option" type="button" data-answer="${esc(o)}"><span>${String.fromCharCode(65+i)}</span>${esc(o)}</button>`).join('')}</div></div>`;
 activityBody.querySelectorAll('.answer-option').forEach(b=>b.addEventListener('click',()=>checkMCQ(b,q,1)));
}
function checkMCQ(btn,q,section){if(answered)return;answered=true;const a=btn.dataset.answer,buttons=[...activityBody.querySelectorAll('.answer-option')];const correct=a===q.a||a===q.answer;buttons.forEach(b=>{b.disabled=true;if(b.dataset.answer===(q.a||q.answer))b.classList.add('is-correct')});if(!correct)btn.classList.add('is-wrong');if(correct){score++;activityFeedback.innerHTML=`<strong class="feedback-good">✓ Chính xác!</strong> ${q.why||q.explanation}`}else activityFeedback.innerHTML=`<strong class="feedback-bad">✗ Chưa đúng.</strong> Đáp án đúng là <b>${esc(q.a||q.answer)}</b>. ${q.why||q.explanation}`}
function showFinalWarmUp(){setHeader('KHỞI ĐỘNG • HOÀN THÀNH','Tuyệt vời! Em đã khởi động xong.','Hãy xem kết quả trước khi chuyển sang phần Từ vựng.','✓');activityBody.innerHTML=`<div class="result-card"><div class="result-score">${score}<span>/${warmUpQuestions.length}</span></div><div><h3>Kết quả khởi động</h3><p>${score===warmUpQuestions.length?'Rất tốt! Em đã sẵn sàng học Unit 1.':'Em hãy xem lại phần giải thích rồi tiếp tục nhé.'}</p></div></div>${completion('Hoàn thành phần Khởi động!')}`;activityFeedback.textContent='';nextActivity.textContent='Sang Từ vựng →'}
function renderVocabulary(){
 setHeader('TỪ VỰNG • VOCABULARY','My New School — Vocabulary','Học từ mới, nghe phát âm và ghi nhớ nghĩa tiếng Việt.',`${vocabulary.length} từ`);
 activityBody.innerHTML=`<div class="vocab-grid">${vocabulary.map(v=>`<div class="vocab-card"><div><div class="vocab-word">${v[0]}</div><div class="vocab-meta">${v[1]} · ${v[2]}</div><div class="vocab-meaning">${v[3]}</div></div><button class="listen-word" type="button" data-word="${v[0]}">🔊 Nghe UK</button></div>`).join('')}</div><div class="grammar-box"><h3>3 bước nhớ từ</h3><div class="grammar-rule">Nhìn từ → nghe phát âm → đặt câu. Khi quên, em cứ tra lại. Tra nhiều lần chính là một cách ôn tập.</div></div>${completion('Bộ từ vựng Unit 1 đã sẵn sàng!')}`;
 activityBody.querySelectorAll('.listen-word').forEach(b=>b.addEventListener('click',()=>speak(b.dataset.word)));nextActivity.textContent='Sang Ngữ pháp →'}
function renderGrammar(){
 setHeader('NGỮ PHÁP • GRAMMAR','Present Simple','Nắm quy tắc rồi làm 4 câu luyện tập có giải thích.',`${grammarQuestions.length} câu`);
 activityBody.innerHTML=`<div class="grammar-box"><h3>Công thức cốt lõi</h3><div class="formula">I / You / We / They + V</div><div class="formula">He / She / It + V-s/es</div><div class="formula">Do/Does + S + V?</div><div class="example-line"><b>Example:</b> I go to school every day. / She goes to school every day.</div></div><div class="practice-grid">${grammarQuestions.map((q,i)=>`<div class="mini-exercise" data-gi="${i}"><h3>Câu ${i+1}. ${esc(q.q)}</h3><div class="mini-options">${shuffleOptions(q.opts).map(o=>`<button type="button" data-a="${esc(o)}">${esc(o)}</button>`).join('')}</div><div class="mini-explain" id="gexp${i}"></div></div>`).join('')}</div>${completion('Em đã ôn xong phần Ngữ pháp!')}`;
 activityBody.querySelectorAll('.mini-exercise').forEach(card=>card.querySelectorAll('button').forEach(btn=>btn.addEventListener('click',()=>miniMCQ(btn,card,grammarQuestions[Number(card.dataset.gi)]))));nextActivity.textContent='Sang Luyện tập →'}
function miniMCQ(btn,card,q){if(card.dataset.done)return;card.dataset.done='1';const buttons=[...card.querySelectorAll('button')],correct=btn.dataset.a===q.a;buttons.forEach(b=>{b.disabled=true;if(b.dataset.a===q.a)b.classList.add('correct')});if(!correct)btn.classList.add('wrong');card.querySelector('.mini-explain').innerHTML=correct?`<span class="feedback-good">✓ Đúng.</span> ${q.why}`:`<span class="feedback-bad">✗ Chưa đúng.</span> Đáp án: <b>${q.a}</b>. ${q.why}`}
function renderPractice(){
 setHeader('LUYỆN TẬP • PRACTICE','Practice & Writing','Làm trắc nghiệm rồi chuyển sang phần viết. Đáp án viết chỉ hiện sau khi em tự kiểm tra.',`${practiceQuestions.length+writingQuestions.length} bài`);
 activityBody.innerHTML=`<div class="practice-grid">${practiceQuestions.map((q,i)=>`<div class="mini-exercise"><h3>Câu ${i+1}. ${esc(q.q)}</h3><div class="mini-options">${shuffleOptions(q.opts).map(o=>`<button type="button" data-a="${esc(o)}">${esc(o)}</button>`).join('')}</div><div class="mini-explain"></div></div>`).join('')}</div><div class="challenge-section-title">PHẦN VIẾT — TỰ LUẬN</div><p class="challenge-intro">Hãy tự làm trước. Khi bấm “Kiểm tra”, hệ thống mới đưa phản hồi và câu mẫu.</p>${writingQuestions.map((w,i)=>`<div class="writing-card" data-wi="${i}"><h3>Viết ${i+1}</h3><div class="writing-prompt">${esc(w.prompt)}</div><textarea class="writing-input" placeholder="Nhập câu trả lời bằng tiếng Anh..."></textarea><div class="writing-actions"><button class="check-writing" type="button">Kiểm tra bài viết</button><span class="writing-result"></span></div><div class="sample-answer" id="sample${i}"><b>Gợi ý / bài mẫu:</b> ${esc(w.answer)}<br><span>${esc(w.note)}</span></div></div>`).join('')}${completion('Phần Luyện tập đã có cả trắc nghiệm và tự luận!')}`;
 activityBody.querySelectorAll('.mini-exercise').forEach(card=>{const q=practiceQuestions[[...activityBody.querySelectorAll('.mini-exercise')].indexOf(card)];card.querySelectorAll('button').forEach(btn=>btn.addEventListener('click',()=>miniMCQ(btn,card,q)))});
 activityBody.querySelectorAll('.writing-card').forEach(card=>{const w=writingQuestions[Number(card.dataset.wi)];card.querySelector('.check-writing').addEventListener('click',()=>checkWriting(card,w))});nextActivity.textContent='Sang Đọc hiểu →'}
function checkWriting(card,w){const input=card.querySelector('.writing-input'),result=card.querySelector('.writing-result'),sample=card.querySelector('.sample-answer'),text=normalize(input.value);if(!text){result.className='writing-result bad';result.textContent='Hãy viết câu trả lời trước nhé.';return}const exact=normalize(w.answer)===text;const keywords=(w.keywords||[]).every(k=>text.includes(normalize(k)));result.className=`writing-result ${exact||keywords?'good':'bad'}`;result.textContent=exact?'✓ Chính xác!':keywords?'✓ Câu của em có các ý chính phù hợp. Hãy xem bài mẫu để tự kiểm tra ngữ pháp.':'△ Chưa đủ ý hoặc có thể còn lỗi. Hãy xem bài mẫu để đối chiếu.';sample.classList.add('show')}
function renderReading(){
 setHeader('ĐỌC HIỂU • READING','A New School Day','Đọc kỹ đoạn văn, sau đó trả lời 3 câu hỏi.',`3 câu`);
 activityBody.innerHTML=`<div class="reading-box"><h3>Reading</h3><div class="reading-text"><b>My new school</b><br>My name is Nam. I am a student at a new school. It is near my house, so I walk to school every morning. My school has three floors and a large playground. There are many classrooms, a library and a computer room. I like the library most because I love reading. My classmates are friendly, and my teachers are helpful.</div><div class="reading-questions">${readingQuestions.map((q,i)=>`<div class="reading-q"><p>Câu ${i+1}. ${esc(q.q)}</p><div class="mini-options">${shuffleOptions(q.opts).map(o=>`<button type="button" data-a="${esc(o)}">${esc(o)}</button>`).join('')}</div><div class="mini-explain"></div></div>`).join('')}</div></div>${completion('Em đã hoàn thành phần Đọc hiểu!')}`;
 activityBody.querySelectorAll('.reading-q').forEach((card,i)=>card.querySelectorAll('button').forEach(btn=>btn.addEventListener('click',()=>miniMCQ(btn,card,readingQuestions[i]))));nextActivity.textContent='Sang Nói →'}
function renderSpeaking(){
 setHeader('NÓI • SPEAKING','Talk about My New School','Dùng từ gợi ý để tự nói. Động từ được giữ ở nguyên mẫu để em tự vận dụng.',`Speaking`);
 activityBody.innerHTML=`<div class="speaking-box"><h3>Task</h3><p>Talk about your new school in 4–5 sentences.</p><div class="prompt-list"><div class="prompt-item"><b>school</b> · <b>classroom</b> · <b>classmates</b></div><div class="prompt-item"><b>be</b> · <b>have</b> · <b>like</b> · <b>study</b> · <b>play</b></div><div class="prompt-item"><b>near</b> · <b>big</b> · <b>friendly</b> · <b>usually</b></div></div><h3>Bài nói mẫu</h3><div class="speaking-sample">My new school is near my house. It has many classrooms and a big playground. My classmates are friendly. I usually study English in the morning. I like my new school.</div><div class="writing-actions"><button class="audio-chip" id="speak-sample" type="button">🔊 Nghe bài mẫu</button></div><div class="speaking-note">Lưu ý: hãy tự chia động từ theo chủ ngữ khi nói. Ví dụ: I study, but She studies.</div></div>${completion('Em đã có đủ gợi ý để luyện nói!')}`;
 document.querySelector('#speak-sample').addEventListener('click',()=>speak('My new school is near my house. It has many classrooms and a big playground. My classmates are friendly. I usually study English in the morning. I like my new school.'));nextActivity.textContent='Sang Thử thách →'}
function renderChallenge(){
 setHeader('THỬ THÁCH • ADVANCED','Unit 1 Challenge — Nâng cao','10 bài: 6 trắc nghiệm nâng cao + 4 bài viết. Hãy làm chậm và đọc kỹ.',`10 bài`);
 activityBody.innerHTML=`<div class="challenge-box"><div class="score-strip"><span>Điểm thử thách</span><strong id="challenge-score">0 / 10</strong></div><p class="challenge-intro">Mục tiêu: kiểm tra khả năng vận dụng, không chỉ nhớ đáp án. Với phần viết, em tự làm trước rồi mới bấm kiểm tra.</p><div class="challenge-section-title">A. TRẮC NGHIỆM NÂNG CAO</div><div class="challenge-grid">${challengeMCQ.map((q,i)=>`<div class="mini-exercise challenge-mcq" data-ci="${i}"><h3>Câu ${i+1}. ${esc(q.q)}</h3><div class="mini-options">${shuffleOptions(q.opts).map(o=>`<button type="button" data-a="${esc(o)}">${esc(o)}</button>`).join('')}</div><div class="mini-explain"></div></div>`).join('')}</div><div class="challenge-section-title">B. VIẾT NÂNG CAO</div>${challengeWriting.map((w,i)=>`<div class="writing-card challenge-writing" data-wi="${i}"><h3>Câu ${i+7}</h3><div class="writing-prompt">${esc(w.prompt)}</div><textarea class="writing-input" placeholder="Viết câu trả lời bằng tiếng Anh..."></textarea><div class="writing-actions"><button class="check-writing" type="button">Kiểm tra</button><span class="writing-result"></span></div><div class="sample-answer"><b>Bài mẫu:</b> ${esc(w.answer)}<br><span>${esc(w.note)}</span></div></div>`).join('')}</div>${completion('Thử thách Unit 1 đã hoàn thành!')}`;
 activityBody.querySelectorAll('.challenge-mcq').forEach(card=>{const q=challengeMCQ[Number(card.dataset.ci)];card.querySelectorAll('button').forEach(btn=>btn.addEventListener('click',()=>{if(card.dataset.done)return;card.dataset.done='1';const correct=btn.dataset.a===q.a;card.querySelectorAll('button').forEach(b=>{b.disabled=true;if(b.dataset.a===q.a)b.classList.add('correct')});if(!correct)btn.classList.add('wrong');if(correct)score++;card.querySelector('.mini-explain').innerHTML=correct?`<span class="feedback-good">✓ Đúng.</span> ${q.why}`:`<span class="feedback-bad">✗ Chưa đúng.</span> Đáp án: <b>${esc(q.a)}</b>. ${q.why}`;updateChallengeScore()})});
 activityBody.querySelectorAll('.challenge-writing').forEach(card=>{const w=challengeWriting[Number(card.dataset.wi)];card.querySelector('.check-writing').addEventListener('click',()=>{const input=card.querySelector('.writing-input'),result=card.querySelector('.writing-result'),sample=card.querySelector('.sample-answer'),text=normalize(input.value);if(!text){result.className='writing-result bad';result.textContent='Hãy viết trước nhé.';return}const keywords=(w.keywords||[]).every(k=>text.includes(normalize(k)));const enough=text.split(' ').length>=5;result.className=`writing-result ${keywords&&enough?'good':'bad'}`;result.textContent=keywords&&enough?'✓ Bài viết có đủ ý chính. Hãy đối chiếu bài mẫu để tự sửa lỗi.':'△ Hãy kiểm tra lại cấu trúc câu, từ khóa và độ đầy đủ của ý.';sample.classList.add('show');card.dataset.checked='1';updateChallengeScore()})});nextActivity.textContent='Hoàn tất Unit 1 ✓'}
function updateChallengeScore(){const doneMCQ=[...document.querySelectorAll('.challenge-mcq[data-done]')].length;const doneWriting=[...document.querySelectorAll('.challenge-writing[data-checked]')].length;document.querySelector('#challenge-score').textContent=`${Math.min(score,10)} / 10`;if(doneMCQ+doneWriting===10)activityFeedback.innerHTML='<strong class="feedback-good">✓ Đã hoàn thành đủ 10 bài thử thách.</strong> Hãy xem lại các câu còn sai và sửa bài viết.'}
function renderPlaceholder(n){const names=['Khởi động','Từ vựng','Ngữ pháp','Luyện tập','Đọc hiểu','Nói','Thử thách'];activityLabel.textContent=`PHẦN ${String(n).padStart(2,'0')}`;contentTitle.textContent=names[n-1];contentInstruction.textContent='Nội dung của phần học.';activityBadge.textContent=`${n} / ${totalSteps}`;activityBody.innerHTML='';}
function renderStep(n){if(n===1){previewPanel.classList.add('show');currentQuestion=0;score=0;renderWarmUp()}else{previewPanel.classList.remove('show');if(n===2)renderVocabulary();if(n===3)renderGrammar();if(n===4)renderPractice();if(n===5)renderReading();if(n===6)renderSpeaking();if(n===7){score=0;renderChallenge()}}}
steps.forEach(s=>s.addEventListener('click',()=>{selectStep(Number(s.dataset.step));lessonActivity.scrollIntoView({behavior:'smooth',block:'center'})}));
document.querySelector('#start-activity').addEventListener('click',()=>{currentQuestion=0;score=0;selectStep(1);lessonActivity.scrollIntoView({behavior:'smooth',block:'center'})});
nextActivity.addEventListener('click',()=>{if(document.querySelector('.answer-option')){if(!answered){activityFeedback.innerHTML='<strong class="feedback-bad">Hãy chọn một đáp án trước nhé.</strong>';return}if(currentQuestion<warmUpQuestions.length-1){currentQuestion++;renderWarmUp();return}showFinalWarmUp();return}const active=Number(document.querySelector('.step.is-active')?.dataset.step||1);if(active<totalSteps){selectStep(active+1);lessonActivity.scrollIntoView({behavior:'smooth',block:'center'})}else{activityFeedback.innerHTML='<strong class="feedback-good">✓ Tuyệt vời!</strong> Em đã đi hết 7 phần của Unit 1.'}});
soundToggle.addEventListener('click',()=>{const enabled=soundToggle.getAttribute('aria-pressed')!=='true';soundToggle.setAttribute('aria-pressed',String(enabled));toast.textContent=enabled?'Đã bật âm thanh hướng dẫn!':'Đã tắt âm thanh hướng dẫn!';toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2600)});
renderStep(1);