(() => {
  const style = document.createElement('style');
  style.textContent = `#text-lookup{position:fixed;z-index:99999;width:min(370px,calc(100vw - 24px));background:#fff;border:1px solid #dfe6f0;border-radius:16px;box-shadow:0 16px 45px rgba(36,54,83,.18);padding:15px;color:#293b5c;font-family:var(--body-font)}#text-lookup[hidden]{display:none}.lookup-top{display:flex;justify-content:space-between;gap:12px}.lookup-word{font:800 22px/1.2 var(--display-font);margin:0}.lookup-meta{color:#74839a;font-size:12px;margin-top:4px}.lookup-close{border:0;background:#f1f4f8;border-radius:8px;width:28px;height:28px;cursor:pointer}.lookup-meaning{margin-top:11px;padding-top:11px;border-top:1px solid #edf0f5;font-size:14px;line-height:1.5}.lookup-label{color:#8b98aa;font-size:10px;font-weight:800;letter-spacing:1px;text-transform:uppercase}.lookup-actions{display:flex;gap:8px;margin-top:12px}.lookup-speak{border:0;border-radius:9px;background:#3959a9;color:#fff;padding:8px 11px;cursor:pointer;font:800 12px var(--body-font)}.lookup-note{color:#8b98aa;font-size:11px;margin-top:9px}.lookup-vn{font-size:16px;font-weight:700;color:#243653}`;
  document.head.appendChild(style);

  const box=document.createElement('aside');box.id='text-lookup';box.hidden=true;box.setAttribute('role','dialog');document.body.appendChild(box);
  const local={
    school:['noun','/skuːl/','trường học'],classroom:['noun','/ˈklɑːs.ruːm/','phòng học, lớp học'],classmate:['noun','/ˈklɑːs.meɪt/','bạn cùng lớp'],student:['noun','/ˈstjuː.dənt/','học sinh'],teacher:['noun','/ˈtiː.tʃər/','giáo viên'],lesson:['noun','/ˈles.ən/','bài học'],subject:['noun','/ˈsʌb.dʒɪkt/','môn học'],book:['noun','/bʊk/','sách'],notebook:['noun','/ˈnəʊ.bʊk/','vở, sổ tay'],friend:['noun','/frend/','bạn'],schoolbag:['noun','/ˈskuːl.bæɡ/','cặp sách'],pen:['noun','/pen/','bút mực'],pencil:['noun','/ˈpen.səl/','bút chì'],ruler:['noun','/ˈruː.lər/','thước kẻ'],desk:['noun','/desk/','bàn học'],chair:['noun','/tʃeər/','ghế'],library:['noun','/ˈlaɪ.brər.i/','thư viện'],playground:['noun','/ˈpleɪ.ɡraʊnd/','sân chơi'],uniform:['noun','/ˈjuː.nɪ.fɔːm/','đồng phục'],new:['adjective','/njuː/','mới'],good:['adjective','/ɡʊd/','tốt'],happy:['adjective','/ˈhæp.i/','vui, hạnh phúc'],learn:['verb','/lɜːn/','học'],study:['verb','/ˈstʌd.i/','học, học tập'],start:['verb','/stɑːt/','bắt đầu'],meet:['verb','/miːt/','gặp'],getup:['phrasal verb','/ɡet ʌp/','thức dậy, đứng dậy'],wakeup:['phrasal verb','/weɪk ʌp/','thức dậy'],lookfor:['phrasal verb','/lʊk fɔːr/','tìm kiếm'],listen:['verb','/ˈlɪs.ən/','nghe'],listen to:['phrasal verb','/ˈlɪs.ən tuː/','lắng nghe'],go to:['phrasal verb','/ɡəʊ tuː/','đi đến']
  };
  const phrasal=new Set('get up|wake up|look for|listen to|go to|look at|look after|turn on|turn off|put on|take off|sit down|stand up|pick up|give up|grow up|hang out|write down|talk about'.split('|'));
  const esc=s=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  const clean=s=>s.replace(/[‘’]/g,"'").replace(/[“”]/g,'"').replace(/\s+/g,' ').trim();
  const key=s=>s.toLowerCase().replace(/[^a-z\s]/g,'').replace(/\s+/g,'');
  const isWord=s=>/^[A-Za-z][A-Za-z'-]*$/.test(s);
  const isPhrasal=s=>phrasal.has(s.toLowerCase());
  function speak(t){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='en-GB';u.rate=.82;const v=speechSynthesis.getVoices().find(x=>/^en-GB$/i.test(x.lang));if(v)u.voice=v;speechSynthesis.speak(u)}
  function pos(x,y){box.style.left=Math.min(Math.max(12,x),window.innerWidth-box.offsetWidth-12)+'px';box.style.top=Math.min(Math.max(12,y+12),window.innerHeight-box.offsetHeight-12)+'px'}
  function close(){box.hidden=true}
  function render(text,meta,vn){box.innerHTML='<div class="lookup-top"><div><h3 class="lookup-word">'+esc(text)+'</h3><div class="lookup-meta">'+esc(meta)+'</div></div><button class="lookup-close" type="button">×</button></div><div class="lookup-meaning"><div class="lookup-label">Nghĩa tiếng Việt</div><div class="lookup-vn">'+esc(vn)+'</div></div><div class="lookup-actions"><button class="lookup-speak" type="button">🔊 Nghe tiếng Anh UK</button></div>';box.querySelector('.lookup-close').onclick=close;box.querySelector('.lookup-speak').onclick=()=>speak(text)}
  async function remoteWord(text){try{const d=await(await fetch('https://api.dictionaryapi.dev/api/v2/entries/en/'+encodeURIComponent(text))).json();const e=d?.[0],m=e?.meanings?.[0];return {pos:m?.partOfSpeech||'English word',ipa:e?.phonetic||e?.phonetics?.find(x=>x.text)?.text||'',def:m?.definitions?.[0]?.definition||''}}catch{return null}}
  async function remoteVi(text){try{const d=await(await fetch('https://api.mymemory.translated.net/get?q='+encodeURIComponent(text)+'&langpair=en|vi')).json();return d?.responseData?.translatedText||''}catch{return ''}}
  async function show(raw,x,y){const text=clean(raw);if(!text||text.length>180)return;box.hidden=false;box.innerHTML='<div class="lookup-top"><div><h3 class="lookup-word">'+esc(text)+'</h3><div class="lookup-meta">Đang tra cứu…</div></div><button class="lookup-close">×</button></div>';box.querySelector('.lookup-close').onclick=close;pos(x,y);const k=key(text);const localInfo=local[k];if(localInfo){render(text,localInfo[0]+' · '+localInfo[1],localInfo[2]);pos(x,y);return}
    if(isWord(text)||isPhrasal(text)){const info=isWord(text)?await remoteWord(text):null;const vn=await remoteVi(text);render(text,(isPhrasal(text)?'phrasal verb':(info?.pos||'English word'))+(info?.ipa?' · '+info.ipa:''),vn||'Chưa tìm thấy nghĩa tiếng Việt.');pos(x,y);return}
    const vn=await remoteVi(text);render(text,'Cụm từ / câu',vn||'Chưa lấy được bản dịch.');pos(x,y)
  }
  document.addEventListener('mouseup',e=>{if(box.contains(e.target))return;setTimeout(()=>{const s=window.getSelection();if(!s||s.isCollapsed)return;const t=s.toString().trim();if(!t)return;const r=s.getRangeAt(0).getBoundingClientRect();show(t,r.left,r.bottom)},30)});
  document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});
})();
