const units=[
{id:1,title:'My New School',theme:'Trường học, môn học và những ngày đầu ở trường mới',grammar:'Present Simple + Adverbs of frequency',pron:'/ɑː/ và /ʌ/',skills:'Reading about schools; talking about school type; listening about school activities; writing about a school',sections:[['Khởi động','Getting Started','Làm quen với một ngày học mới; hội thoại, hiểu ý chính và nhận diện đồ dùng học tập.'],['Từ vựng','A Closer Look 1','School subjects, school activities và nhóm động từ play / do / have / study; luyện âm /ɑː/ và /ʌ/.'],['Ngữ pháp','A Closer Look 2','Hiện tại đơn và trạng từ tần suất; khẳng định, phủ định, câu hỏi và vị trí trạng từ.'],['Luyện tập','Communication','Giới thiệu bạn mới, hỏi–đáp về sở thích và hoạt động ở trường.'],['Đọc hiểu','Skills 1 – Reading','Đọc và so sánh thông tin về các trường học; tìm thông tin chi tiết và suy luận đơn giản.'],['Nói','Skills 1 – Speaking / Skills 2 – Listening','Nói về trường mình thích; luyện nghe thông tin về một trường học và kiểm tra đáp án.'],['Thử thách','Skills 2 – Writing / Looking Back / Project','Viết đoạn giới thiệu trường; tổng hợp từ vựng–ngữ pháp; thiết kế và thuyết trình dream school.']]},
{id:2,title:'My House',theme:'Ngôi nhà, các phòng và đồ nội thất',grammar:'Possessive case + Prepositions of place',pron:'Âm cuối /s/ và /z/',skills:'Reading about rooms and furniture; describing houses; listening about a house; writing an email',sections:[['Khởi động','Getting Started','Làm quen với ngôi nhà và các thành viên trong gia đình; nghe–đọc và xác định thông tin.'],['Từ vựng','A Closer Look 1','Các loại nhà, phòng và đồ nội thất; phân nhóm từ và luyện phát âm âm cuối.'],['Ngữ pháp','A Closer Look 2','Sở hữu cách và giới từ chỉ vị trí; mô tả đồ vật ở đâu trong phòng.'],['Luyện tập','Communication','Mô tả ngôi nhà, hỏi–đáp về nơi ở và trao đổi thông tin với bạn.'],['Đọc hiểu','Skills 1 – Reading','Đọc về các căn phòng/đồ nội thất và tìm thông tin cụ thể.'],['Nói','Skills 1 – Speaking / Skills 2 – Listening','Mô tả nhà hoặc căn phòng; nghe và xác định vị trí/thông tin.'],['Thử thách','Skills 2 – Writing / Looking Back / Project','Viết email mô tả nhà; tổng hợp kiến thức; lựa chọn và trình bày ngôi nhà em muốn sống.']]},
{id:3,title:'My Friends',theme:'Bạn bè, ngoại hình và tính cách',grammar:'Present Continuous',pron:'Âm /b/ và /p/',skills:'Reading about friends and summer camps; talking about friends; listening about best friends; diary writing',sections:[['Khởi động','Getting Started','Làm quen với bạn bè và hoạt động cùng bạn; nghe–đọc và hiểu nhân vật, tình huống.'],['Từ vựng','A Closer Look 1','Bộ phận cơ thể, ngoại hình và tính cách; kết hợp từ với hình/định nghĩa.'],['Ngữ pháp','A Closer Look 2','Hiện tại tiếp diễn để nói về hành động đang diễn ra; câu khẳng định, phủ định và hỏi.'],['Luyện tập','Communication','Hỏi–đáp về ngoại hình và tính cách; chia sẻ thông tin về một người bạn.'],['Đọc hiểu','Skills 1 – Reading','Đọc về bạn bè và các trại hè; tìm ý chính và thông tin chi tiết.'],['Nói','Skills 1 – Speaking / Skills 2 – Listening','Nói về người bạn và hoạt động cùng bạn; nghe về người bạn thân.'],['Thử thách','Skills 2 – Writing / Looking Back / Project','Viết nhật ký về bạn thân; tổng hợp ngôn ngữ; giới thiệu bạn và phẩm chất nổi bật.']]},
{id:4,title:'My Neighbourhood',theme:'Khu phố, địa điểm và cách chỉ đường',grammar:'Comparative adjectives',pron:'Âm /ɪ/ và /iː/',skills:'Reading about a neighbourhood; talking about a neighbourhood; listening; describing a neighbourhood',sections:[['Khởi động','Getting Started','Tình huống tìm đường trong khu phố; nghe–đọc và nhận diện các địa điểm.'],['Từ vựng','A Closer Look 1','Các địa điểm trong khu phố và cách gọi tên; luyện phát âm mục tiêu.'],['Ngữ pháp','A Closer Look 2','So sánh hơn của tính từ để so sánh đường phố, địa điểm và khu vực.'],['Luyện tập','Communication','Hỏi và chỉ đường; dùng ngôn ngữ giao tiếp phù hợp.'],['Đọc hiểu','Skills 1 – Reading','Đọc về một khu phố và tìm thông tin về địa điểm, đặc điểm.'],['Nói','Skills 1 – Speaking / Skills 2 – Listening','Nói về khu phố; nghe thông tin và xác định địa điểm/đặc điểm.'],['Thử thách','Skills 2 – Writing / Looking Back / Project','Viết đoạn mô tả khu phố; so sánh địa điểm; tạo bản đồ khu phố và thuyết trình.']]},
{id:5,title:'Natural Wonders of Viet Nam',theme:'Kỳ quan thiên nhiên và du lịch',grammar:"Countable / uncountable nouns + must / mustn't",pron:'Âm /t/ và /d/',skills:'Reading about natural wonders; talking about famous places; listening; writing about a natural wonder',sections:[['Khởi động','Getting Started','Khám phá các kỳ quan thiên nhiên Việt Nam qua hội thoại và hình ảnh.'],['Từ vựng','A Closer Look 1','Từ về thiên nhiên và đồ dùng khi đi du lịch; phân loại và luyện phát âm.'],['Ngữ pháp','A Closer Look 2',"Danh từ đếm được/không đếm được; must và mustn't để nói điều cần/không được làm."],['Luyện tập','Communication','Trao đổi về địa điểm nổi tiếng, hoạt động và điều cần chuẩn bị.'],['Đọc hiểu','Skills 1 – Reading','Đọc về kỳ quan thiên nhiên và tìm thông tin về vị trí, đặc điểm, hoạt động.'],['Nói','Skills 1 – Speaking / Skills 2 – Listening','Nói về nơi nổi tiếng; nghe thông tin chuyến đi và kiểm tra hiểu.'],['Thử thách','Skills 2 – Writing / Looking Back / Project','Viết về một kỳ quan; dùng must/mustn’t chính xác; tạo poster Dream Destination.']]},
{id:6,title:'Our Tet Holiday',theme:'Tết, phong tục và hoạt động ngày Tết',grammar:"Should / shouldn't + Some / any",pron:'Âm /s/ và /ʃ/',skills:'Reading about New Year practices; talking about what children should/shouldn’t do; listening about Tet preparation; writing an email',sections:[['Khởi động','Getting Started','Làm quen với Tết và những hoạt động chuẩn bị, gặp gỡ, chúc mừng.'],['Từ vựng','A Closer Look 1','Đồ dùng và hoạt động ngày Tết; nhóm từ và luyện âm /s/ và /ʃ/.'],['Ngữ pháp','A Closer Look 2','Should/shouldn’t để đưa lời khuyên; some/any để nói về lượng.'],['Luyện tập','Communication','Nói lời chúc, hỏi–đáp và trao đổi về việc nên/không nên làm trong dịp Tết.'],['Đọc hiểu','Skills 1 – Reading','Đọc về phong tục đón năm mới và tìm thông tin quan trọng.'],['Nói','Skills 1 – Speaking / Skills 2 – Listening','Thảo luận những việc nên/không nên làm; nghe về việc chuẩn bị Tết.'],['Thử thách','Skills 2 – Writing / Looking Back / Project','Viết email về Tết; tổng hợp kiến thức; thực hiện hoạt động I Wish.']]}
];
const reviews=[
{id:'review1',title:'Review 1 – Units 1–2–3',focus:'Pronunciation · Vocabulary · Present Simple · Present Continuous · Possessive case · Prepositions of place',skills:'Reading · Speaking · Listening · Writing'},
{id:'review2',title:'Review 2 – Units 4–5–6',focus:"Pronunciation · Vocabulary · Comparative adjectives · Countable/uncountable nouns · must/mustn't · should/shouldn't · some/any",skills:'Reading · Speaking · Listening · Writing'}
];
const grid=document.querySelector('#unit-grid');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function unitCard(u){return `<article class="card"><div class="num">UNIT ${u.id.toString().padStart(2,'0')}</div><div style="color:#d62828;font-weight:800;font-size:12px;line-height:1.35;margin:5px 0 8px">By Nguyen Duc Dai<br>TH&amp;THCS ĐỒNG TÂM</div><h2>${esc(u.title)}</h2><div class="theme">${esc(u.theme)}</div><div class="meta"><span class="tag">${esc(u.grammar)}</span><span class="tag">${esc(u.pron)}</span></div><div class="sections">${u.sections.map(s=>`<div class="section"><b>${esc(s[0])} · ${esc(s[1])}</b><span>${esc(s[2])}</span></div>`).join('')}</div><a class="open" href="${u.id===1?'index.html':'#'}" ${u.id!==1?'onclick="alert(\'Khung nội dung của Unit này đã sẵn sàng.\');return false;"':''}>${u.id===1?'Mở Unit 1 →':'Mở Unit '+u.id+' →'}</a></article>`}
function reviewCard(r){return `<article class="card review"><div class="num">ÔN TẬP</div><div style="color:#d62828;font-weight:800;font-size:12px;line-height:1.35;margin:5px 0 8px">By Nguyen Duc Dai<br>TH&amp;THCS ĐỒNG TÂM</div><h2>${esc(r.title)}</h2><div class="theme"><b>Trọng tâm:</b> ${esc(r.focus)}</div><div class="theme" style="margin-top:8px"><b>Kỹ năng:</b> ${esc(r.skills)}</div><a class="open" href="#" onclick="alert('Phần Review sẽ dùng cùng hệ thống chấm điểm, giải thích và bài tự luận của Unit.');return false;">Mở Review →</a></article>`}
grid.innerHTML=units.map(unitCard).join('')+reviews.map(reviewCard).join('');